version: '2'
services:
    web:
        build: .
        command: python3 app.py
        ports:
            - "80:5000"
        volumes:
            - .:/code:Z
            - ./user:/home/app:Z
        depends_on:
            - redis
    redis:
        image: redis

    navidrome:
        image: deluan/navidrome:latest
#        user: 1000:1000 # should be owner of volumes
        ports:
            - "4533:4533"
        restart: unless-stopped
        environment:
            # Optional: put your config options customization here. Examples:
            ND_SCANSCHEDULE: 1h
            ND_LOGLEVEL: info
            ND_SESSIONTIMEOUT: 24h
#            ND_BASEURL: ""
        volumes:
            - "./navidrome:/data:Z"
            - "/home/stonesoft/Music:/music:ro"
